//! Fractal control-plane SDK surface.
//!
//! The single source of truth for this surface is
//! `interfaces/wit/fractalos-capabilities-v1/capabilities.wit`. Everything
//! below is re-exported from the bindings generated by `wit_bindgen::generate!`
//! in [`crate::wit_generated`]; no ABI type is re-declared by hand. The
//! generated surface keeps explicit `Result` values and distinct typed
//! handles (`ProgramHandle`, `TaskHandle`, `SubscriptionHandle`,
//! `AgentHandle`) so capability seams cannot be crossed with the wrong token.
//!
//! The generated code is `no_std`-compatible: the `std_feature` generator
//! option gates `std::error::Error` implementations behind this crate's own
//! `std` feature, so enabling `wit-bindings` never implies `std`.

/// Capability seams imported by the `agent-runtime-v1` world. Each module
/// carries the effect-class documented on its WIT functions.
pub use crate::wit_generated::fractalos::capabilities::{
    action, actors, budget, events, model, object_store, state, task_verifier, workspace,
};

/// The asynchronous task control plane a runtime exports to candidates.
pub use crate::wit_generated::exports::fractalos::capabilities::task_control_plane;

/// Implementors of the exported `task-control-plane` interface.
pub use crate::wit_generated::exports::fractalos::capabilities::task_control_plane::Guest as TaskControlPlane;

/// Shared provider-neutral values from the WIT `common-types` interface.
pub use crate::wit_generated::fractalos::capabilities::common_types::{
    AgentHandle, Constraints, EffectClass, ErrorCode, ObjectId, ObjectResult, ScopeClass,
    SubscriptionHandle,
};

/// Types of the exported `task-control-plane` interface.
pub use crate::wit_generated::exports::fractalos::capabilities::task_control_plane::{
    Budget, Digest, ProgramHandle, ProgramRef, ProgramState, ProofLevel, State, Submission,
    TaskError, TaskHandle, TerminalResult, VerifyEvidence, VerifyStatus, WorkerIdentity,
    WorkerKind,
};

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    /// A control plane that answers immediately; every method keeps the
    /// generated `Result` shape, and nothing waits for a worker.
    struct ImmediatePlane;

    impl TaskControlPlane for ImmediatePlane {
        fn open_program(
            reference: ProgramRef,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<ProgramHandle, TaskError> {
            Ok(ProgramHandle {
                id: 1,
                authority_epoch: reference.interface_version,
            })
        }

        fn poll_program(
            _program: ProgramHandle,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<ProgramState, TaskError> {
            Ok(ProgramState::Ready)
        }

        fn submit(
            program: ProgramHandle,
            _budget: Budget,
            authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<Submission, TaskError> {
            Ok(Submission {
                program,
                task: TaskHandle {
                    id: 9,
                    authority_epoch,
                },
                state: State::Accepted,
                authority_epoch,
                worker: WorkerIdentity {
                    kind: WorkerKind::Native,
                    slot: 0,
                    generation: 1,
                },
            })
        }

        fn poll(
            _task: TaskHandle,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<State, TaskError> {
            Ok(State::Running)
        }

        fn cancel(
            task: TaskHandle,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<State, TaskError> {
            if task.id == 9 {
                Ok(State::Cancelled)
            } else {
                Err(TaskError::NotFound)
            }
        }

        fn set_budget(
            _task: TaskHandle,
            budget: Budget,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<Budget, TaskError> {
            Ok(budget)
        }

        fn task_verify(
            _task: TaskHandle,
            evidence: VerifyEvidence,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<VerifyStatus, TaskError> {
            if evidence.evidence_version == 2 {
                Ok(VerifyStatus::Accepted)
            } else {
                Err(TaskError::EvidenceMismatch)
            }
        }

        fn get_terminal_result(
            _task: TaskHandle,
            _authority_epoch: u32,
            _nonblocking: bool,
        ) -> Result<TerminalResult, TaskError> {
            Ok(TerminalResult {
                state: State::Complete,
                result_kind: 1,
                terminal_code: 0,
                result_bytes: 4,
                verify_status: VerifyStatus::Accepted,
                worker: WorkerIdentity {
                    kind: WorkerKind::Native,
                    slot: 0,
                    generation: 1,
                },
                result_digest: vec![0x44; 32],
            })
        }
    }

    #[test]
    fn explicit_results_flow_through_the_control_plane() {
        let reference = ProgramRef {
            digest: vec![0x11; 32],
            program_version: 1,
            interface_version: 1,
        };
        let program = ImmediatePlane::open_program(reference, 7, true)
            .expect("open-program is an explicit Result");
        let submission = ImmediatePlane::submit(
            program,
            Budget {
                cpu_quanta: 100,
                memory_bytes: 4096,
                max_steps: 10,
                max_result_bytes: 512,
            },
            7,
            true,
        )
        .expect("submit is an explicit Result");
        assert_eq!(submission.state, State::Accepted);
        assert_eq!(
            ImmediatePlane::poll(submission.task, 7, true),
            Ok(State::Running)
        );
        assert_eq!(
            ImmediatePlane::cancel(submission.task, 7, true),
            Ok(State::Cancelled)
        );
        assert_eq!(
            ImmediatePlane::poll(
                TaskHandle {
                    id: 404,
                    authority_epoch: 7
                },
                7,
                true
            ),
            Ok(State::Running)
        );
        assert_eq!(
            ImmediatePlane::cancel(
                TaskHandle {
                    id: 404,
                    authority_epoch: 7
                },
                7,
                true
            ),
            Err(TaskError::NotFound)
        );
    }

    #[test]
    fn typed_handles_stay_distinct() {
        // Each handle keeps its own generated type; the wrong token cannot
        // satisfy a seam (these coercions pin the exact signatures).
        let subscribe: fn(ObjectId, &Constraints) -> Result<SubscriptionHandle, ErrorCode> =
            events::subscribe;
        let spawn: fn(ObjectId, &Constraints) -> Result<AgentHandle, ErrorCode> = actors::spawn;
        let limits = Constraints {
            budget_units: 1,
            deadline_ticks: 2,
            allowed_effects: alloc::vec![EffectClass::EventRead],
        };
        assert_eq!(limits.allowed_effects.len(), 1);
        // The seam functions themselves only execute inside a component; on
        // the host their typed signatures are pinned by the coercions above.
        let _ = (subscribe, spawn);
        let task = TaskHandle {
            id: 3,
            authority_epoch: 1,
        };
        // Passing `task` where a ProgramHandle is required does not compile;
        // route it through the control plane that owns the transition.
        let program = ImmediatePlane::open_program(
            ProgramRef {
                digest: vec![0; 32],
                program_version: 1,
                interface_version: 2,
            },
            1,
            true,
        )
        .expect("handle transition stays typed");
        assert_ne!(program.id, task.id);
        assert_eq!(
            ImmediatePlane::poll_program(program, 1, true),
            Ok(ProgramState::Ready)
        );
    }

    #[test]
    fn canonical_task_verify_evidence_is_version_two() {
        let evidence = VerifyEvidence {
            evidence_version: 2,
            proof_level: ProofLevel::TargetContract,
            test_count: 12,
            commit_digest: vec![0x22; 32],
            test_digest: vec![0x33; 32],
            evidence_digest: vec![0x44; 32],
        };
        let status = ImmediatePlane::task_verify(
            TaskHandle {
                id: 5,
                authority_epoch: 1,
            },
            evidence,
            1,
            true,
        );
        assert_eq!(status, Ok(VerifyStatus::Accepted));
        let legacy = VerifyEvidence {
            evidence_version: 1,
            proof_level: ProofLevel::HostContract,
            test_count: 1,
            commit_digest: vec![0; 32],
            test_digest: vec![0; 32],
            evidence_digest: vec![0; 32],
        };
        assert_eq!(
            ImmediatePlane::task_verify(
                TaskHandle {
                    id: 5,
                    authority_epoch: 1
                },
                legacy,
                1,
                true
            ),
            Err(TaskError::EvidenceMismatch)
        );
    }

    #[test]
    fn error_surface_is_no_std_compatible() {
        // Errors are Display through core in every configuration; the
        // std::error::Error implementation exists only under the crate's
        // `std` feature (asserted separately below).
        fn assert_display<T: core::fmt::Display>(value: &T) -> alloc::string::String {
            alloc::format!("{value}")
        }
        assert!(!assert_display(&TaskError::VerifyRequired).is_empty());
        assert!(!assert_display(&ErrorCode::Denied).is_empty());
    }

    #[cfg(feature = "std")]
    #[test]
    fn std_error_impl_follows_the_std_feature() {
        fn assert_std_error<T: std::error::Error>(_: &T) {}
        assert_std_error(&TaskError::VerifyRequired);
        assert_std_error(&ErrorCode::Denied);
    }

    #[test]
    fn object_results_carry_typed_follow_up_handles() {
        let ready = ObjectResult::Ready(ObjectId {
            word0: 1,
            word1: 2,
            word2: 3,
            word3: 4,
        });
        let ObjectResult::Ready(id) = ready else {
            panic!("ready object id is not pending work");
        };
        assert_eq!(id.word3, 4);
        let pending = ObjectResult::Pending(TaskHandle {
            id: 6,
            authority_epoch: 1,
        });
        let ObjectResult::Pending(task) = pending else {
            panic!("pending object is not a ready id");
        };
        assert_eq!(task.id, 6);
    }
}
