use crate::GenCapsArgs;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const SYSTEM_MAX_PDS: u32 = 64;
const SLOTS_PER_PD: u32 = 6;

#[derive(Deserialize, Debug)]
struct SystemDesc {
    #[serde(default)]
    pd: Vec<PdDesc>,
}

#[derive(Deserialize, Debug)]
struct PdDesc {
    name: String,
    #[serde(default)]
    priority: u8,
}

pub fn run(args: &GenCapsArgs) -> Result<()> {
    let selected = select_system_toml(&args.system, &args.board_system);
    let desc = load_system(&selected)?;
    let header = render_header(&selected, &desc)?;

    if let Some(parent) = args.out.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    std::fs::write(&args.out, header)
        .with_context(|| format!("failed to write {}", args.out.display()))?;
    println!(
        "[gen-caps] wrote {} from {} ({} PDs)",
        args.out.display(),
        selected.display(),
        desc.pd.len()
    );
    Ok(())
}

fn select_system_toml(base: &Path, board_overrides: &[PathBuf]) -> PathBuf {
    for candidate in board_overrides {
        if candidate.is_file()
            && std::fs::metadata(candidate)
                .map(|m| m.len() > 0)
                .unwrap_or(false)
        {
            return candidate.clone();
        }
    }
    base.to_path_buf()
}

fn load_system(path: &Path) -> Result<SystemDesc> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read system TOML: {}", path.display()))?;
    let desc: SystemDesc = toml::from_str(&text)
        .with_context(|| format!("failed to parse system TOML: {}", path.display()))?;
    anyhow::ensure!(
        desc.pd.len() <= SYSTEM_MAX_PDS as usize,
        "system descriptor has {} PDs, max is {}",
        desc.pd.len(),
        SYSTEM_MAX_PDS
    );
    Ok(desc)
}

fn render_header(source: &Path, desc: &SystemDesc) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "/* Auto-generated by `cargo xtask gen-caps`. */")?;
    writeln!(out, "/* Source: {} */", source.display())?;
    writeln!(out, "#pragma once")?;
    writeln!(out)?;
    writeln!(
        out,
        "#define AGENTOS_CAP_SYSTEM_MAX_PDS {}u",
        SYSTEM_MAX_PDS
    )?;
    writeln!(out, "#define AGENTOS_CAP_SLOTS_PER_PD {}u", SLOTS_PER_PD)?;
    writeln!(out, "#define AGENTOS_CAP_PD_COUNT {}u", desc.pd.len())?;
    writeln!(out)?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_CNODE(i)      ((i) * AGENTOS_CAP_SLOTS_PER_PD + 0u)"
    )?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_TCB(i)        ((i) * AGENTOS_CAP_SLOTS_PER_PD + 1u)"
    )?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_VSPACE(i)     ((i) * AGENTOS_CAP_SLOTS_PER_PD + 2u)"
    )?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_IPC_FRAME(i)  ((i) * AGENTOS_CAP_SLOTS_PER_PD + 3u)"
    )?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_SC(i)         ((i) * AGENTOS_CAP_SLOTS_PER_PD + 4u)"
    )?;
    writeln!(
        out,
        "#define AGENTOS_CAP_PD_SLOT_NTFN(i)       ((i) * AGENTOS_CAP_SLOTS_PER_PD + 5u)"
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "#define AGENTOS_CAP_EP_POOL_BASE_REL      (AGENTOS_CAP_SYSTEM_MAX_PDS * AGENTOS_CAP_SLOTS_PER_PD)"
    )?;
    writeln!(out, "#define AGENTOS_CAP_EP_POOL_SIZE          256u")?;
    writeln!(out)?;

    for (idx, pd) in desc.pd.iter().enumerate() {
        let ident = c_ident(&pd.name);
        writeln!(out, "#define AGENTOS_CAP_PD_{}_INDEX {}u", ident, idx)?;
        writeln!(
            out,
            "#define AGENTOS_CAP_PD_{}_PRIORITY {}u",
            ident, pd.priority
        )?;
    }

    Ok(out)
}

fn c_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            ident.push(ch.to_ascii_uppercase());
        } else {
            ident.push('_');
        }
    }
    if ident.is_empty() || ident.as_bytes()[0].is_ascii_digit() {
        ident.insert(0, '_');
    }
    ident
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_deterministic_layout_for_minimal_descriptor() {
        let desc: SystemDesc = toml::from_str(
            r#"
[[pd]]
name = "nameserver"
priority = 245

[[pd]]
name = "cc-pd"
priority = 160
"#,
        )
        .unwrap();
        let header = render_header(Path::new("agentos.toml"), &desc).unwrap();
        assert!(header.contains("#define AGENTOS_CAP_SYSTEM_MAX_PDS 64u"));
        assert!(header.contains("#define AGENTOS_CAP_SLOTS_PER_PD 6u"));
        assert!(header.contains("#define AGENTOS_CAP_EP_POOL_BASE_REL      (AGENTOS_CAP_SYSTEM_MAX_PDS * AGENTOS_CAP_SLOTS_PER_PD)"));
        assert!(header.contains("#define AGENTOS_CAP_PD_NAMESERVER_INDEX 0u"));
        assert!(header.contains("#define AGENTOS_CAP_PD_CC_PD_INDEX 1u"));
    }

    #[test]
    fn nonempty_board_override_replaces_base_descriptor() {
        let dir = tempfile::tempdir().unwrap();
        let base = dir.path().join("base.toml");
        let board = dir.path().join("board.toml");
        std::fs::write(&base, "[[pd]]\nname = \"base\"\n").unwrap();
        std::fs::write(&board, "[[pd]]\nname = \"board\"\n").unwrap();

        let selected = select_system_toml(&base, &[board.clone()]);
        assert_eq!(selected, board);
    }
}
