timeout: 3
default_entry: 1
verbose: yes
serial: yes
/Fractal marker with hardware recovery watchdog
    protocol: multiboot2
    path: boot():/EFI/FractalWatchdog/sel4_32.elf
    module_path: boot():/EFI/FractalWatchdog/root_task.elf
