//! gen-abi — FractalOS per-PD ABI table generator.
//!
//! Reads the source-of-truth ABI spec (`tools/abi_spec.toml`) and emits a
//! generated C header (`fractalos_abi.h`) containing per-PD ABI tables.
//!
//! The build MUST fail (nonzero exit) when the spec is internally
//! inconsistent. We detect and hard-fail on:
//!   * duplicate opcode value within a single PD's opcode table,
//!   * duplicate channel id within a single PD's channel scope,
//!   * a `contract = "<dir>"` reference with no matching contracts/<dir>/.
//!
//! Drift between a generated value and the hand-written constant it mirrors
//! (`legacy`) is caught at C-compile time: the header emits a `_Static_assert`
//! per entry, so a stale fractalos.h constant fails the C build.

use anyhow::{bail, Context, Result};
use clap::Parser;
use serde::Deserialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

// ── Spec structs ──────────────────────────────────────────────────────── //

#[derive(Deserialize)]
struct Spec {
    #[allow(dead_code)]
    version: String,
    #[serde(default)]
    pd: Vec<PdSpec>,
}

#[derive(Deserialize)]
struct PdSpec {
    name: String,
    /// Optional contracts/<dir> that must exist (contract coverage check).
    contract: Option<String>,
    /// Optional numeric trace PD id (informational, emitted as a #define).
    trace_pd: Option<u32>,
    #[serde(default)]
    opcode: Vec<Entry>,
    #[serde(default)]
    channel: Vec<ChannelEntry>,
}

#[derive(Deserialize)]
struct Entry {
    name: String,
    value: u32,
    /// Existing fractalos.h constant this entry mirrors.
    legacy: Option<String>,
}

#[derive(Deserialize)]
struct ChannelEntry {
    name: String,
    id: u32,
    legacy: Option<String>,
}

// ── Validation ────────────────────────────────────────────────────────── //

/// Run every consistency check. Returns the list of human-readable errors;
/// empty means the spec is sound.
fn validate(spec: &Spec, contracts_root: &Path) -> Vec<String> {
    let mut errors = Vec::new();
    let mut pd_names: HashMap<&str, usize> = HashMap::new();

    for pd in &spec.pd {
        // Duplicate PD name across the whole spec.
        if let Some(prev) = pd_names.insert(pd.name.as_str(), 1) {
            let _ = prev;
            errors.push(format!("duplicate PD name: {}", pd.name));
        }

        // Contract coverage: a referenced contract dir must exist.
        if let Some(contract) = &pd.contract {
            let dir = contracts_root.join(contract);
            if !dir.is_dir() {
                errors.push(format!(
                    "PD '{}' references contract '{}' but {} does not exist (missing contract coverage)",
                    pd.name,
                    contract,
                    dir.display()
                ));
            }
        }

        // Duplicate opcode value within this PD.
        let mut seen_op: HashMap<u32, &str> = HashMap::new();
        for op in &pd.opcode {
            if let Some(prev) = seen_op.insert(op.value, op.name.as_str()) {
                errors.push(format!(
                    "PD '{}': duplicate opcode value 0x{:X} assigned to both '{}' and '{}'",
                    pd.name, op.value, prev, op.name
                ));
            }
        }

        // Duplicate channel id within this PD's channel scope.
        let mut seen_ch: HashMap<u32, &str> = HashMap::new();
        for ch in &pd.channel {
            if let Some(prev) = seen_ch.insert(ch.id, ch.name.as_str()) {
                errors.push(format!(
                    "PD '{}': duplicate channel id {} assigned to both '{}' and '{}'",
                    pd.name, ch.id, prev, ch.name
                ));
            }
        }
    }

    errors
}

// ── Code generation ───────────────────────────────────────────────────── //

fn upper(s: &str) -> String {
    s.to_uppercase()
}

fn generate(spec: &Spec, source_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "/* Generated by gen-abi from: {} — DO NOT EDIT. */\n",
        source_name
    ));
    out.push_str(&format!(
        "/* Regenerate with: cargo run -p gen-abi -- tools/{} \\\n */\n",
        source_name
    ));
    out.push_str("/*     -o kernel/fractalos-root-task/include/fractalos_abi.h   */\n\n");
    out.push_str("#pragma once\n");
    out.push_str("#ifndef FRACTALOS_ABI_H\n");
    out.push_str("#define FRACTALOS_ABI_H\n\n");
    out.push_str("#include <stdint.h>\n\n");
    out.push_str(
        "/*\n * Per-PD ABI tables. Each PD's opcodes and channels live in their own\n\
         \x20* namespace: ABI_<PD>_OP_<NAME> for opcodes, ABI_<PD>_CH_<NAME> for\n\
         \x20* channels. Values are guaranteed collision-free within each PD by the\n\
         \x20* generator (gen-abi fails the build on any duplicate).\n */\n\n",
    );

    // Per-PD constant blocks.
    for pd in &spec.pd {
        let pdu = upper(&pd.name);
        out.push_str(&format!(
            "/* ── PD: {} ─────────────────────────────────────────── */\n",
            pd.name
        ));
        if let Some(tp) = pd.trace_pd {
            out.push_str(&format!("#define ABI_{}_TRACE_PD {}u\n", pdu, tp));
        }
        if let Some(c) = &pd.contract {
            out.push_str(&format!(
                "/* contract: contracts/{}/ (coverage verified by gen-abi) */\n",
                c
            ));
        }
        out.push_str(&format!(
            "#define ABI_{}_OPCODE_COUNT {}u\n",
            pdu,
            pd.opcode.len()
        ));
        out.push_str(&format!(
            "#define ABI_{}_CHANNEL_COUNT {}u\n",
            pdu,
            pd.channel.len()
        ));
        for op in &pd.opcode {
            out.push_str(&format!(
                "#define ABI_{}_OP_{} 0x{:X}u\n",
                pdu,
                upper(&op.name),
                op.value
            ));
        }
        for ch in &pd.channel {
            out.push_str(&format!(
                "#define ABI_{}_CH_{} {}u\n",
                pdu,
                upper(&ch.name),
                ch.id
            ));
        }
        out.push('\n');
    }

    // Drift guard: tie each generated value to the legacy constant.
    out.push_str(
        "/*\n * Stale-constant guard. Each _Static_assert ties a generated ABI value\n\
         \x20* to the hand-written constant in fractalos.h it mirrors. If fractalos.h\n\
         \x20* drifts from this generated table, the C build fails here.\n\
         \x20* (Skipped for the gen-abi unit tests / standalone preprocessing.)\n */\n",
    );
    out.push_str("#ifdef FRACTALOS_ABI_CHECK_LEGACY\n");
    for pd in &spec.pd {
        let pdu = upper(&pd.name);
        for op in &pd.opcode {
            if let Some(legacy) = &op.legacy {
                out.push_str(&format!(
                    "_Static_assert((uint32_t)({}) == ABI_{}_OP_{}, \"fractalos.h {} drifted from abi_spec.toml\");\n",
                    legacy, pdu, upper(&op.name), legacy
                ));
            }
        }
        for ch in &pd.channel {
            if let Some(legacy) = &ch.legacy {
                out.push_str(&format!(
                    "_Static_assert((uint32_t)({}) == ABI_{}_CH_{}, \"fractalos.h {} drifted from abi_spec.toml\");\n",
                    legacy, pdu, upper(&ch.name), legacy
                ));
            }
        }
    }
    out.push_str("#endif /* FRACTALOS_ABI_CHECK_LEGACY */\n\n");

    out.push_str("#endif /* FRACTALOS_ABI_H */\n");
    out
}

// ── CLI ───────────────────────────────────────────────────────────────── //

#[derive(Parser)]
#[command(name = "gen-abi", about = "FractalOS per-PD ABI table generator")]
struct Cli {
    /// TOML ABI spec file (source of truth).
    spec: PathBuf,

    /// Output .h file.
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// contracts/ root used for the contract-coverage check.
    #[arg(long, default_value = "contracts")]
    contracts: PathBuf,

    /// Validate the spec and exit without writing files.
    #[arg(long)]
    check: bool,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let content = std::fs::read_to_string(&cli.spec)
        .with_context(|| format!("failed to read {}", cli.spec.display()))?;
    let spec: Spec = toml::from_str(&content).with_context(|| "TOML parse error in ABI spec")?;

    let errors = validate(&spec, &cli.contracts);
    if !errors.is_empty() {
        eprintln!("gen-abi: ABI spec validation FAILED:");
        for e in &errors {
            eprintln!("  x {}", e);
        }
        // Hard-fail the build.
        bail!(
            "{} ABI spec error(s); refusing to emit header",
            errors.len()
        );
    }

    let source_name = cli
        .spec
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("abi_spec.toml")
        .to_string();

    if cli.check {
        println!(
            "OK: ABI spec valid — {} PD(s), {} opcode(s), {} channel(s)",
            spec.pd.len(),
            spec.pd.iter().map(|p| p.opcode.len()).sum::<usize>(),
            spec.pd.iter().map(|p| p.channel.len()).sum::<usize>(),
        );
        return Ok(());
    }

    let code = generate(&spec, &source_name);
    let out_path = cli
        .output
        .unwrap_or_else(|| PathBuf::from("fractalos_abi.h"));
    std::fs::write(&out_path, &code)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    println!("OK: generated {}", out_path.display());
    Ok(())
}

// ── Tests ─────────────────────────────────────────────────────────────── //

#[cfg(test)]
mod tests {
    use super::*;

    fn op(name: &str, value: u32) -> Entry {
        Entry {
            name: name.to_string(),
            value,
            legacy: Some(format!("MSG_{}", name)),
        }
    }
    fn ch(name: &str, id: u32) -> ChannelEntry {
        ChannelEntry {
            name: name.to_string(),
            id,
            legacy: Some(format!("CH_{}", name)),
        }
    }
    fn pd(name: &str, contract: Option<&str>, ops: Vec<Entry>, chs: Vec<ChannelEntry>) -> PdSpec {
        PdSpec {
            name: name.to_string(),
            contract: contract.map(|s| s.to_string()),
            trace_pd: None,
            opcode: ops,
            channel: chs,
        }
    }
    fn spec(pds: Vec<PdSpec>) -> Spec {
        Spec {
            version: "1".into(),
            pd: pds,
        }
    }
    /// A contracts root guaranteed not to contain the referenced dir.
    fn no_contracts() -> PathBuf {
        PathBuf::from("/nonexistent-contracts-root-xyz")
    }

    #[test]
    fn clean_spec_passes() {
        let s = spec(vec![pd(
            "event_bus",
            None,
            vec![op("INIT", 1), op("STATUS", 2)],
            vec![ch("MONITOR", 1), ch("INITAGENT", 2)],
        )]);
        let errs = validate(&s, &no_contracts());
        assert!(errs.is_empty(), "expected clean, got {:?}", errs);
    }

    #[test]
    fn duplicate_opcode_fails() {
        let s = spec(vec![pd(
            "event_bus",
            None,
            vec![op("INIT", 1), op("STATUS", 1)],
            vec![],
        )]);
        let errs = validate(&s, &no_contracts());
        assert!(
            errs.iter().any(|e| e.contains("duplicate opcode")),
            "expected duplicate-opcode error, got {:?}",
            errs
        );
    }

    #[test]
    fn duplicate_channel_fails() {
        let s = spec(vec![pd(
            "event_bus",
            None,
            vec![],
            vec![ch("A", 5), ch("B", 5)],
        )]);
        let errs = validate(&s, &no_contracts());
        assert!(
            errs.iter().any(|e| e.contains("duplicate channel id")),
            "expected duplicate-channel error, got {:?}",
            errs
        );
    }

    #[test]
    fn missing_contract_fails() {
        let s = spec(vec![pd(
            "block_pd",
            Some("does-not-exist"),
            vec![op("OPEN", 1)],
            vec![],
        )]);
        let errs = validate(&s, &no_contracts());
        assert!(
            errs.iter().any(|e| e.contains("missing contract coverage")),
            "expected contract-coverage error, got {:?}",
            errs
        );
    }

    #[test]
    fn same_opcode_in_different_pds_is_ok() {
        // Per-PD namespace: value 1 in two PDs is NOT a collision.
        let s = spec(vec![
            pd("a", None, vec![op("X", 1)], vec![]),
            pd("b", None, vec![op("Y", 1)], vec![]),
        ]);
        let errs = validate(&s, &no_contracts());
        assert!(
            errs.is_empty(),
            "cross-PD same value should be ok, got {:?}",
            errs
        );
    }

    #[test]
    fn generate_emits_per_pd_constants_and_asserts() {
        let s = spec(vec![pd(
            "event_bus",
            None,
            vec![op("INIT", 1)],
            vec![ch("MONITOR", 2)],
        )]);
        let code = generate(&s, "abi_spec.toml");
        assert!(code.contains("#define ABI_EVENT_BUS_OP_INIT 0x1u"));
        assert!(code.contains("#define ABI_EVENT_BUS_CH_MONITOR 2u"));
        assert!(code.contains("_Static_assert"));
        assert!(code.contains("FRACTALOS_ABI_CHECK_LEGACY"));
    }
}
