/* Generated by gen-abi from: abi_spec.toml — DO NOT EDIT. */
/* Regenerate with: cargo run -p gen-abi -- tools/abi_spec.toml \
 */
/*     -o kernel/fractalos-root-task/include/fractalos_abi.h   */

#pragma once
#ifndef FRACTALOS_ABI_H
#define FRACTALOS_ABI_H

#include <stdint.h>

/*
 * Per-PD ABI tables. Each PD's opcodes and channels live in their own
 * namespace: ABI_<PD>_OP_<NAME> for opcodes, ABI_<PD>_CH_<NAME> for
 * channels. Values are guaranteed collision-free within each PD by the
 * generator (gen-abi fails the build on any duplicate).
 */

/* ── PD: companion_export ─────────────────────────────────────────── */
#define ABI_COMPANION_EXPORT_OPCODE_COUNT 7u
#define ABI_COMPANION_EXPORT_CHANNEL_COUNT 1u
#define ABI_COMPANION_EXPORT_OP_DESCRIBE 0x2F01u
#define ABI_COMPANION_EXPORT_OP_LIST_PROJECTS 0x2F02u
#define ABI_COMPANION_EXPORT_OP_LIST_PROGRESS 0x2F03u
#define ABI_COMPANION_EXPORT_OP_GET_DAILY_ROOT 0x2F04u
#define ABI_COMPANION_EXPORT_OP_GET_HEALTH_ADAPTER 0x2F05u
#define ABI_COMPANION_EXPORT_OP_LIST_WORKER_MEMORY 0x2F06u
#define ABI_COMPANION_EXPORT_OP_SUBMIT_TASK_INTENT 0x2F07u
#define ABI_COMPANION_EXPORT_CH_CONTROLLER 77u

/* ── PD: event_bus ─────────────────────────────────────────── */
#define ABI_EVENT_BUS_TRACE_PD 1u
/* contract: contracts/event-bus/ (coverage verified by gen-abi) */
#define ABI_EVENT_BUS_OPCODE_COUNT 6u
#define ABI_EVENT_BUS_CHANNEL_COUNT 2u
#define ABI_EVENT_BUS_OP_INIT 0x1u
#define ABI_EVENT_BUS_OP_SUBSCRIBE 0x2u
#define ABI_EVENT_BUS_OP_UNSUBSCRIBE 0x3u
#define ABI_EVENT_BUS_OP_STATUS 0x4u
#define ABI_EVENT_BUS_OP_PUBLISH_BATCH 0x5u
#define ABI_EVENT_BUS_OP_QUERY_SUBSCRIBERS 0x2701u
#define ABI_EVENT_BUS_CH_MONITOR 1u
#define ABI_EVENT_BUS_CH_INITAGENT 2u

/* ── PD: watchdog_pd ─────────────────────────────────────────── */
#define ABI_WATCHDOG_PD_TRACE_PD 24u
#define ABI_WATCHDOG_PD_OPCODE_COUNT 6u
#define ABI_WATCHDOG_PD_CHANNEL_COUNT 2u
#define ABI_WATCHDOG_PD_OP_REGISTER 0x50u
#define ABI_WATCHDOG_PD_OP_HEARTBEAT 0x51u
#define ABI_WATCHDOG_PD_OP_STATUS 0x52u
#define ABI_WATCHDOG_PD_OP_UNREGISTER 0x53u
#define ABI_WATCHDOG_PD_OP_FREEZE 0x54u
#define ABI_WATCHDOG_PD_OP_RESUME 0x55u
#define ABI_WATCHDOG_PD_CH_CTRL 56u
#define ABI_WATCHDOG_PD_CH_NOTIFY 54u

/* ── PD: trace_recorder ─────────────────────────────────────────── */
#define ABI_TRACE_RECORDER_TRACE_PD 25u
#define ABI_TRACE_RECORDER_OPCODE_COUNT 4u
#define ABI_TRACE_RECORDER_CHANNEL_COUNT 2u
#define ABI_TRACE_RECORDER_OP_START 0x80u
#define ABI_TRACE_RECORDER_OP_STOP 0x81u
#define ABI_TRACE_RECORDER_OP_QUERY 0x82u
#define ABI_TRACE_RECORDER_OP_DUMP 0x83u
#define ABI_TRACE_RECORDER_CH_CTRL 6u
#define ABI_TRACE_RECORDER_CH_NOTIFY 7u

/* ── PD: vm_manager ─────────────────────────────────────────── */
#define ABI_VM_MANAGER_OPCODE_COUNT 14u
#define ABI_VM_MANAGER_CHANNEL_COUNT 1u
#define ABI_VM_MANAGER_OP_CREATE 0x10u
#define ABI_VM_MANAGER_OP_DESTROY 0x11u
#define ABI_VM_MANAGER_OP_START 0x12u
#define ABI_VM_MANAGER_OP_STOP 0x13u
#define ABI_VM_MANAGER_OP_PAUSE 0x14u
#define ABI_VM_MANAGER_OP_RESUME 0x15u
#define ABI_VM_MANAGER_OP_CONSOLE 0x16u
#define ABI_VM_MANAGER_OP_INFO 0x17u
#define ABI_VM_MANAGER_OP_LIST 0x18u
#define ABI_VM_MANAGER_OP_SNAPSHOT 0x19u
#define ABI_VM_MANAGER_OP_RESTORE 0x1Au
#define ABI_VM_MANAGER_OP_CONFIGURE 0x1Bu
#define ABI_VM_MANAGER_OP_SEND_INPUT 0x1Fu
#define ABI_VM_MANAGER_OP_CONSOLE_DRAIN 0x20u
#define ABI_VM_MANAGER_CH_MANAGER 45u

/* ── PD: cc_pd ─────────────────────────────────────────── */
#define ABI_CC_PD_TRACE_PD 43u
#define ABI_CC_PD_OPCODE_COUNT 6u
#define ABI_CC_PD_CHANNEL_COUNT 1u
#define ABI_CC_PD_OP_CONNECT 0x2601u
#define ABI_CC_PD_OP_DISCONNECT 0x2602u
#define ABI_CC_PD_OP_SEND 0x2603u
#define ABI_CC_PD_OP_RECV 0x2604u
#define ABI_CC_PD_OP_STATUS 0x2605u
#define ABI_CC_PD_OP_LIST 0x2606u
#define ABI_CC_PD_CH_PD 72u

/* ── PD: vibe_engine ─────────────────────────────────────────── */
#define ABI_VIBE_ENGINE_TRACE_PD 12u
/* contract: contracts/vibeos/ (coverage verified by gen-abi) */
#define ABI_VIBE_ENGINE_OPCODE_COUNT 11u
#define ABI_VIBE_ENGINE_CHANNEL_COUNT 1u
#define ABI_VIBE_ENGINE_OP_CREATE 0x2401u
#define ABI_VIBE_ENGINE_OP_DESTROY 0x2402u
#define ABI_VIBE_ENGINE_OP_STATUS 0x2403u
#define ABI_VIBE_ENGINE_OP_LIST 0x2404u
#define ABI_VIBE_ENGINE_OP_BIND_DEVICE 0x2405u
#define ABI_VIBE_ENGINE_OP_UNBIND_DEVICE 0x2406u
#define ABI_VIBE_ENGINE_OP_SNAPSHOT 0x2407u
#define ABI_VIBE_ENGINE_OP_RESTORE 0x2408u
#define ABI_VIBE_ENGINE_OP_MIGRATE 0x2409u
#define ABI_VIBE_ENGINE_OP_SUSPEND 0x2410u
#define ABI_VIBE_ENGINE_OP_RESUME 0x2411u
#define ABI_VIBE_ENGINE_CH_ENGINE 40u

/* ── PD: block_pd ─────────────────────────────────────────── */
/* contract: contracts/block-service/ (coverage verified by gen-abi) */
#define ABI_BLOCK_PD_OPCODE_COUNT 7u
#define ABI_BLOCK_PD_CHANNEL_COUNT 1u
#define ABI_BLOCK_PD_OP_OPEN 0x2201u
#define ABI_BLOCK_PD_OP_CLOSE 0x2202u
#define ABI_BLOCK_PD_OP_READ 0x2203u
#define ABI_BLOCK_PD_OP_WRITE 0x2204u
#define ABI_BLOCK_PD_OP_FLUSH 0x2205u
#define ABI_BLOCK_PD_OP_STATUS 0x2206u
#define ABI_BLOCK_PD_OP_TRIM 0x2207u
#define ABI_BLOCK_PD_CH_PD 49u

/* ── PD: usb_pd ─────────────────────────────────────────── */
/* contract: contracts/usb-service/ (coverage verified by gen-abi) */
#define ABI_USB_PD_OPCODE_COUNT 8u
#define ABI_USB_PD_CHANNEL_COUNT 1u
#define ABI_USB_PD_OP_ENUMERATE 0x2301u
#define ABI_USB_PD_OP_LIST 0x2302u
#define ABI_USB_PD_OP_OPEN 0x2303u
#define ABI_USB_PD_OP_CLOSE 0x2304u
#define ABI_USB_PD_OP_CONTROL 0x2305u
#define ABI_USB_PD_OP_BULK_IN 0x2306u
#define ABI_USB_PD_OP_BULK_OUT 0x2307u
#define ABI_USB_PD_OP_STATUS 0x2308u
#define ABI_USB_PD_CH_PD 50u

/*
 * Stale-constant guard. Each _Static_assert ties a generated ABI value
 * to the hand-written constant in fractalos.h it mirrors. If fractalos.h
 * drifts from this generated table, the C build fails here.
 * (Skipped for the gen-abi unit tests / standalone preprocessing.)
 */
#ifdef FRACTALOS_ABI_CHECK_LEGACY
_Static_assert((uint32_t)(MSG_COMPANION_DESCRIBE) == ABI_COMPANION_EXPORT_OP_DESCRIBE, "fractalos.h MSG_COMPANION_DESCRIBE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_LIST_PROJECTS) == ABI_COMPANION_EXPORT_OP_LIST_PROJECTS, "fractalos.h MSG_COMPANION_LIST_PROJECTS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_LIST_PROGRESS) == ABI_COMPANION_EXPORT_OP_LIST_PROGRESS, "fractalos.h MSG_COMPANION_LIST_PROGRESS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_GET_DAILY_ROOT) == ABI_COMPANION_EXPORT_OP_GET_DAILY_ROOT, "fractalos.h MSG_COMPANION_GET_DAILY_ROOT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_GET_HEALTH_ADAPTER) == ABI_COMPANION_EXPORT_OP_GET_HEALTH_ADAPTER, "fractalos.h MSG_COMPANION_GET_HEALTH_ADAPTER drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_LIST_WORKER_MEMORY) == ABI_COMPANION_EXPORT_OP_LIST_WORKER_MEMORY, "fractalos.h MSG_COMPANION_LIST_WORKER_MEMORY drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_COMPANION_SUBMIT_TASK_INTENT) == ABI_COMPANION_EXPORT_OP_SUBMIT_TASK_INTENT, "fractalos.h MSG_COMPANION_SUBMIT_TASK_INTENT drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_COMPANION_EXPORT) == ABI_COMPANION_EXPORT_CH_CONTROLLER, "fractalos.h CH_COMPANION_EXPORT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_INIT) == ABI_EVENT_BUS_OP_INIT, "fractalos.h MSG_EVENTBUS_INIT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_SUBSCRIBE) == ABI_EVENT_BUS_OP_SUBSCRIBE, "fractalos.h MSG_EVENTBUS_SUBSCRIBE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_UNSUBSCRIBE) == ABI_EVENT_BUS_OP_UNSUBSCRIBE, "fractalos.h MSG_EVENTBUS_UNSUBSCRIBE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_STATUS) == ABI_EVENT_BUS_OP_STATUS, "fractalos.h MSG_EVENTBUS_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_PUBLISH_BATCH) == ABI_EVENT_BUS_OP_PUBLISH_BATCH, "fractalos.h MSG_EVENTBUS_PUBLISH_BATCH drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_EVENTBUS_QUERY_SUBSCRIBERS) == ABI_EVENT_BUS_OP_QUERY_SUBSCRIBERS, "fractalos.h MSG_EVENTBUS_QUERY_SUBSCRIBERS drifted from abi_spec.toml");
_Static_assert((uint32_t)(EVENTBUS_CH_MONITOR) == ABI_EVENT_BUS_CH_MONITOR, "fractalos.h EVENTBUS_CH_MONITOR drifted from abi_spec.toml");
_Static_assert((uint32_t)(EVENTBUS_CH_INITAGENT) == ABI_EVENT_BUS_CH_INITAGENT, "fractalos.h EVENTBUS_CH_INITAGENT drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_REGISTER) == ABI_WATCHDOG_PD_OP_REGISTER, "fractalos.h OP_WD_REGISTER drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_HEARTBEAT) == ABI_WATCHDOG_PD_OP_HEARTBEAT, "fractalos.h OP_WD_HEARTBEAT drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_STATUS) == ABI_WATCHDOG_PD_OP_STATUS, "fractalos.h OP_WD_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_UNREGISTER) == ABI_WATCHDOG_PD_OP_UNREGISTER, "fractalos.h OP_WD_UNREGISTER drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_FREEZE) == ABI_WATCHDOG_PD_OP_FREEZE, "fractalos.h OP_WD_FREEZE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_WD_RESUME) == ABI_WATCHDOG_PD_OP_RESUME, "fractalos.h OP_WD_RESUME drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_WATCHDOG_CTRL) == ABI_WATCHDOG_PD_CH_CTRL, "fractalos.h CH_WATCHDOG_CTRL drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_WATCHDOG_NOTIFY) == ABI_WATCHDOG_PD_CH_NOTIFY, "fractalos.h CH_WATCHDOG_NOTIFY drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_TRACE_START) == ABI_TRACE_RECORDER_OP_START, "fractalos.h OP_TRACE_START drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_TRACE_STOP) == ABI_TRACE_RECORDER_OP_STOP, "fractalos.h OP_TRACE_STOP drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_TRACE_QUERY) == ABI_TRACE_RECORDER_OP_QUERY, "fractalos.h OP_TRACE_QUERY drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_TRACE_DUMP) == ABI_TRACE_RECORDER_OP_DUMP, "fractalos.h OP_TRACE_DUMP drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_TRACE_CTRL) == ABI_TRACE_RECORDER_CH_CTRL, "fractalos.h CH_TRACE_CTRL drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_TRACE_NOTIFY) == ABI_TRACE_RECORDER_CH_NOTIFY, "fractalos.h CH_TRACE_NOTIFY drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_CREATE) == ABI_VM_MANAGER_OP_CREATE, "fractalos.h OP_VM_CREATE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_DESTROY) == ABI_VM_MANAGER_OP_DESTROY, "fractalos.h OP_VM_DESTROY drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_START) == ABI_VM_MANAGER_OP_START, "fractalos.h OP_VM_START drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_STOP) == ABI_VM_MANAGER_OP_STOP, "fractalos.h OP_VM_STOP drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_PAUSE) == ABI_VM_MANAGER_OP_PAUSE, "fractalos.h OP_VM_PAUSE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_RESUME) == ABI_VM_MANAGER_OP_RESUME, "fractalos.h OP_VM_RESUME drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_CONSOLE) == ABI_VM_MANAGER_OP_CONSOLE, "fractalos.h OP_VM_CONSOLE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_INFO) == ABI_VM_MANAGER_OP_INFO, "fractalos.h OP_VM_INFO drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_LIST) == ABI_VM_MANAGER_OP_LIST, "fractalos.h OP_VM_LIST drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_SNAPSHOT) == ABI_VM_MANAGER_OP_SNAPSHOT, "fractalos.h OP_VM_SNAPSHOT drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_RESTORE) == ABI_VM_MANAGER_OP_RESTORE, "fractalos.h OP_VM_RESTORE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_CONFIGURE) == ABI_VM_MANAGER_OP_CONFIGURE, "fractalos.h OP_VM_CONFIGURE drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_SEND_INPUT) == ABI_VM_MANAGER_OP_SEND_INPUT, "fractalos.h OP_VM_SEND_INPUT drifted from abi_spec.toml");
_Static_assert((uint32_t)(OP_VM_CONSOLE_DRAIN) == ABI_VM_MANAGER_OP_CONSOLE_DRAIN, "fractalos.h OP_VM_CONSOLE_DRAIN drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_VM_MANAGER) == ABI_VM_MANAGER_CH_MANAGER, "fractalos.h CH_VM_MANAGER drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_CONNECT) == ABI_CC_PD_OP_CONNECT, "fractalos.h MSG_CC_CONNECT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_DISCONNECT) == ABI_CC_PD_OP_DISCONNECT, "fractalos.h MSG_CC_DISCONNECT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_SEND) == ABI_CC_PD_OP_SEND, "fractalos.h MSG_CC_SEND drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_RECV) == ABI_CC_PD_OP_RECV, "fractalos.h MSG_CC_RECV drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_STATUS) == ABI_CC_PD_OP_STATUS, "fractalos.h MSG_CC_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_CC_LIST) == ABI_CC_PD_OP_LIST, "fractalos.h MSG_CC_LIST drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_CC_PD) == ABI_CC_PD_CH_PD, "fractalos.h CH_CC_PD drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_CREATE) == ABI_VIBE_ENGINE_OP_CREATE, "fractalos.h MSG_VIBEOS_CREATE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_DESTROY) == ABI_VIBE_ENGINE_OP_DESTROY, "fractalos.h MSG_VIBEOS_DESTROY drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_STATUS) == ABI_VIBE_ENGINE_OP_STATUS, "fractalos.h MSG_VIBEOS_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_LIST) == ABI_VIBE_ENGINE_OP_LIST, "fractalos.h MSG_VIBEOS_LIST drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_BIND_DEVICE) == ABI_VIBE_ENGINE_OP_BIND_DEVICE, "fractalos.h MSG_VIBEOS_BIND_DEVICE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_UNBIND_DEVICE) == ABI_VIBE_ENGINE_OP_UNBIND_DEVICE, "fractalos.h MSG_VIBEOS_UNBIND_DEVICE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_SNAPSHOT) == ABI_VIBE_ENGINE_OP_SNAPSHOT, "fractalos.h MSG_VIBEOS_SNAPSHOT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_RESTORE) == ABI_VIBE_ENGINE_OP_RESTORE, "fractalos.h MSG_VIBEOS_RESTORE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_MIGRATE) == ABI_VIBE_ENGINE_OP_MIGRATE, "fractalos.h MSG_VIBEOS_MIGRATE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_SUSPEND) == ABI_VIBE_ENGINE_OP_SUSPEND, "fractalos.h MSG_VIBEOS_SUSPEND drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_VIBEOS_RESUME) == ABI_VIBE_ENGINE_OP_RESUME, "fractalos.h MSG_VIBEOS_RESUME drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_VIBEENGINE) == ABI_VIBE_ENGINE_CH_ENGINE, "fractalos.h CH_VIBEENGINE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_OPEN) == ABI_BLOCK_PD_OP_OPEN, "fractalos.h MSG_BLOCK_OPEN drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_CLOSE) == ABI_BLOCK_PD_OP_CLOSE, "fractalos.h MSG_BLOCK_CLOSE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_READ) == ABI_BLOCK_PD_OP_READ, "fractalos.h MSG_BLOCK_READ drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_WRITE) == ABI_BLOCK_PD_OP_WRITE, "fractalos.h MSG_BLOCK_WRITE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_FLUSH) == ABI_BLOCK_PD_OP_FLUSH, "fractalos.h MSG_BLOCK_FLUSH drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_STATUS) == ABI_BLOCK_PD_OP_STATUS, "fractalos.h MSG_BLOCK_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_BLOCK_TRIM) == ABI_BLOCK_PD_OP_TRIM, "fractalos.h MSG_BLOCK_TRIM drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_BLOCK_PD) == ABI_BLOCK_PD_CH_PD, "fractalos.h CH_BLOCK_PD drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_ENUMERATE) == ABI_USB_PD_OP_ENUMERATE, "fractalos.h MSG_USB_ENUMERATE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_LIST) == ABI_USB_PD_OP_LIST, "fractalos.h MSG_USB_LIST drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_OPEN) == ABI_USB_PD_OP_OPEN, "fractalos.h MSG_USB_OPEN drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_CLOSE) == ABI_USB_PD_OP_CLOSE, "fractalos.h MSG_USB_CLOSE drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_CONTROL) == ABI_USB_PD_OP_CONTROL, "fractalos.h MSG_USB_CONTROL drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_BULK_IN) == ABI_USB_PD_OP_BULK_IN, "fractalos.h MSG_USB_BULK_IN drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_BULK_OUT) == ABI_USB_PD_OP_BULK_OUT, "fractalos.h MSG_USB_BULK_OUT drifted from abi_spec.toml");
_Static_assert((uint32_t)(MSG_USB_STATUS) == ABI_USB_PD_OP_STATUS, "fractalos.h MSG_USB_STATUS drifted from abi_spec.toml");
_Static_assert((uint32_t)(CH_USB_PD) == ABI_USB_PD_CH_PD, "fractalos.h CH_USB_PD drifted from abi_spec.toml");
#endif /* FRACTALOS_ABI_CHECK_LEGACY */

#endif /* FRACTALOS_ABI_H */
